apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
  namespace: default
  labels:
    deploymentName: app-keda-scale
spec:
  scaleTargetRef:
    deploymentName: app-keda-scale
  pollingInterval: 10
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 15
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-service.monitoring.svc:8080
      metricName: requests_total
      threshold: '30'
      query: sum(rate(requests_total[1m]))
